
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensiondetail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MFRPPensionDetail   
  template:
    metadata:
      labels:
        app: MFRPPensionDetail
    spec:
      containers:
      - name: mfrppensiondetail
        image: pensionmanagementcr.azurecr.io/pensiondetailrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pensionerdetailsn

---
apiVersion: v1
kind: Service
metadata:
  name: mfrppensiondetail
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MFRPPensionDetail